apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::288638064712:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::288638064712:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19LAK80LOW9M2
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-05T13:50:41Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-05T13:50:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1412"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bd0e4161-f196-4a34-a990-09be3927e8a3
